### ISSUE TITLE
Community ID incorrectly requires ports for ICMP

### ISSUE THREAD

**Issue by DylanRJohnston** [traceflight/rs-community-id#3]
Hey all, I've noticed I divergence in computed community-id between Elastic and VRL via this library. If you send the following payload to an Elastic Search container endpoint `POST /_ingest/pipeline/_simulate`

```json
{
    "pipeline": {
        "description": "community_id",
        "processors": [
            {
                "community_id": {
                    "seed": 0
                }
            }
        ]
    },
    "docs": [
        {
            "_source": {
                "source": { 
                    "ip": "10.10.10.10",
                },
                "destination": {
                    "ip": "10.10.10.10",
                },
                "network": {
                    "transport": "icmp"
                }
            }
        }
    ]
}
```

You get the community id `1:4MHSMLtBw+4q7Wke3ztBRVwtgt0=`, however this library requires a destination and source port which if you use the default of `0` produces the community id `1:HNjnAviB6YGcnotXDSmvGJJF1tc=`.

Further more it appears that the community id produced by Elastic is completely independent of the destination and source port numbers, you can put any u16 value for them and it doesn't change the hash. e.g.

 ```json
 {
    "pipeline": {
        "description": "community_id",
        "processors": [
            {
                "community_id": {
                    "seed": 0
                }
            }
        ]
    },
    "docs": [
        {
            "_source": {
                "source": { 
                    "ip": "10.10.10.10",
                    "port": 22
                },
                "destination": {
                    "ip": "10.10.10.10",
                    "port": 433
                },
                "network": {
                    "transport": "icmp"
                }
            }
        }
    ]
}
```

produces the exact same community id `1:4MHSMLtBw+4q7Wke3ztBRVwtgt0=`

If you take a look at the community id spec https://github.com/corelight/community-id-spec it makes the following statements about ICMP

> ICMPv4 / ICMPv6:
>
> IP src / IP dst / IP proto / ICMP type + "counter-type" or code
> 
> The exact handling of ICMP type & code is taken from Zeek; see implementations here:
> 
>     https://github.com/corelight/pycommunityid/blob/master/communityid/icmp.py
>     https://github.com/corelight/pycommunityid/blob/master/communityid/icmp6.py
>     https://github.com/zeek/zeek/blob/master/src/analyzer/protocol/icmp/ICMP.cc#L860

As you can see, the port is not included when calculating the hash for ICMP type and so I believe the behavior and error message from this library is incorrect.

**Comment by DylanRJohnston** [comment]
Ok after reading through the code for both this library, Elastic, and the reference python code I've realised that this library smuggles the ICMP code and type in through the src port and destination port where as Elastic has them as separate arguments. This is why this library reports an error for ICMP missing ports even though it doesn't have ports in the traditional sense. 

The divergence in behavior seems to come from the handling of the default behavior for when the ICMP code and type are missing.

Elastic defaults to zero, but then sends the "ports" through the ICMP flow type mapping. Which interprets the zero as `ECHO` and then sets ICMP type to `ECHO REPLY`. It's not exactly clear what the correct behaviour here is. However both Elastic, and the reference Java implementation seem to do this default mapping.

```sh
>>> import communityid
>>> cid = communityid.CommunityID()
>>> tpl = communityid.FlowTuple.make_icmp('10.10.10.10', '10.10.10.10', 0, 0)
>>> print(cid.calc(tpl))
1:4MHSMLtBw+4q7Wke3ztBRVwtgt0=
```

**Comment by traceflight** [comment]
Close since pr is merged
