### ISSUE TITLE
Divergent handling of IPv6 over IPv4 

### ISSUE THREAD

**Issue by DylanRJohnston** [traceflight/rs-community-id#5]
I came across this while investigating #3 although this one is less clear. Elastic and the reference python implementation will happy compute a community_id for ICMP with IPv6 addresses.

```json
{
    "pipeline": {
        "description": "ICMP with IPv6",
        "processors": [
            {
                "community_id": {
                    "seed": 0
                }
            }
        ]
    },
    "docs": [
        {
            "_source": {
                "source": { 
                    "ip": "2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6"
                },
                "destination": {
                    "ip": "fe00:afa0::1"
                },
                "network": {
                    "iana_number": 1
                }
            }
        }
    ]
}
```
gives the community_id `"1:vW44peXVlakl8z8Pk6oaF4JDxm8="` with the python implementation giving the same answer

```sh
>>> import communityid
>>> cid = communityid.CommunityID()
>>>  tpl = communityid.FlowTuple.make_icmp("2a02:cf40:add:4002:91f2:a9b2:e09a:6fc6", "fe00:afa0::1", 0, 0)
>>> >>> print(cid.calc(tpl))
1:vW44peXVlakl8z8Pk6oaF4JDxm8=
```

This is definitely straying far more into "undefined behavior" territory as the spec has the following to say

```
function community_id_v1(ipaddr saddr, ipaddr daddr, port sport, port dport, int proto, int seed=0)
{
    # Get seed and all tuple parts into network byte order
    seed = pack_to_nbo(seed); # 2 bytes
    saddr = pack_to_nbo(saddr); # 4 or 16 bytes
    daddr = pack_to_nbo(daddr); # 4 or 16 bytes
    sport = pack_to_nbo(sport); # 2 bytes
    dport = pack_to_nbo(dport); # 2 bytes

    # Abstract away directionality: flip the endpoints as needed
    # so the smaller IP:port tuple comes first.
    saddr, daddr, sport, dport = order_endpoints(saddr, daddr, sport, dport);

    # Produce 20-byte SHA1 digest. "." means concatenation. The
    # proto value is one byte in length and followed by a 0 byte
    # for padding.
    sha1_digest = sha1(seed . saddr . daddr . proto . 0 . sport . dport)

    # Prepend version string to base64 rendering of the digest.
    # v1 is currently the only one available.
    return "1:" + base64(sha1_digest)
}

function community_id_icmp(ipaddr saddr, ipaddr daddr, int type, int code, int seed=0)
{
    port sport, dport;

    # ICMP / ICMPv6 endpoint mapping directly inspired by Zeek
    sport, dport = map_icmp_to_ports(type, code);

    # ICMP is IP protocol 1, ICMPv6 would be 58
    return community_id_v1(saddr, daddr, sport, dport, 1, seed); 
}
```

> This version includes the following protocols and fields:
> 
>     TCP / UDP / SCTP:
> 
>     IP src / IP dst / IP proto / source port / dest port
> 
>     ICMPv4 / ICMPv6:
> 
>     IP src / IP dst / IP proto / ICMP type + "counter-type" or code
> 
>     The exact handling of ICMP type & code is taken from Zeek; see implementations here:
>         https://github.com/corelight/pycommunityid/blob/master/communityid/icmp.py
>         https://github.com/corelight/pycommunityid/blob/master/communityid/icmp6.py
>         https://github.com/zeek/zeek/blob/master/src/analyzer/protocol/icmp/ICMP.cc#L860
> 
>     Other IP-borne protocols:
> 
>     IP src / IP dst / IP proto
> 
> The above does not currently cover how to handle nesting (IP in IP, v6 over v4, etc) as well as encapsulations such as VLAN and MPLS.

However I've currently got CISCO networking logs in font of me that unfortunately have ICMP (iana_number = 1) with IPv6 addresses. Such data can also be found in the integration test data for Elastic's Filebeat Cisco ASA module.

Given that the purpose of the community hash is a shared way to identify traffic connections, I think it would make sense to also support this behavior even though it's undefined by the spec.

**Comment by traceflight** [comment]
Close since pr is merged
